### ISSUE TITLE
Tuning speed down doesn't slow extruder speed

### ISSUE THREAD

**Issue by GreenEllipsis** [Nickjallday/RECREATOR#1]
When using Tune menu during extrusion, even using G1 E1 steps, it will NOT let you slow it down, only speed it up. Needed in case the pull speed is unexpectedly too fast. Tried changing the default to F100 in the G-code, and then it won't speed up OR slow down, just went to the original speed, F300(?).

When sending G1 Ex Fxx directly to the machine via Pronterface, there appears to be a minimum speed below which lower F numbers have no effect. Somewhere around F200.

For the first issue, I suspect that Marlin is basing the E speed on the X and Y speeds, but we're not moving the X and Y axes. I don't know if the second issue is related to the first or not. 

Nick, you can assign this to me if you like.

**Comment by GreenEllipsis** [comment]
Submitted Pull Request #2

**Comment by Nickjallday** [comment]
I appreciate the hard work. I'll mark this as completed.
